#!/bin/bash
# 2014.05.29
# Usage: addtime filename

if [[ "x$1" == "x" ||  ! -f $1 ]]
then
 echo "Can't find the file $1."
 exit
fi

d="0"
m="0"
y="0"
i="0"
h="0"

veg=${1##*.}
elej=${1%.*}

echo "d/D; m/M; y/Y; i/I; h/H: decrease/increase Day, Month, Year, mInute, Hour. r: reset; c: cancel; [enter]: ok."

while true; do

stamp=`date -d "$d days $m months $y years $i minutes $h hours" +%y%m%d_%H%M`
if [ "$1" == "${1/\./}" ]
then
 newfnm="$1""_"$stamp
else
 newfnm="$elej""_"$stamp".""$veg"
fi

echo -e -n "\rRenaming to: $newfnm"

 read -s -n 1 key

 if [[ $key == "" ]] ; then
  break
 fi

 if [[ $key == "y" ]] ; then
  ((y--))
 fi

 if [[ $key == "Y" ]] ; then
  ((y++))
 fi

 if [[ $key == "m" ]] ; then
  ((m--))
 fi

 if [[ $key == "M" ]] ; then
  ((m++))
 fi

 if [[ $key == "d" ]] ; then
  ((d--))
 fi

 if [[ $key == "D" ]] ; then
  ((d++))
 fi

 if [[ $key == "h" ]] ; then
  ((h--))
 fi

 if [[ $key == "H" ]] ; then
  ((h++))
 fi

 if [[ $key == "i" ]] ; then
  ((i--))
 fi

 if [[ $key == "I" ]] ; then
  ((i++))
 fi

 if [[ $key == "r" ]] ; then
  y=0
  m=0
  d=0
  h=0
  i=0
 fi

 if [[ $key == "c" ]] ; then
  echo -e "\nHaven't done anything."
  exit
 fi

done

echo -e "\n$1 --> $newfnm"
mv "$1" "$newfnm"
chmod a-w "$newfnm"
