#!/bin/bash

# Cleans up all filenames in the directory.
# Can give optional dir.

if [ "$#" == 0 ]
then
 dir="."
else
 dir="$1"
fi

for i in "$dir"/*
do
#echo "ezafile: $i"
 pathname=${i%/*}
 fn=${i##*/}
 if [ -f "$i" ]
 then
  newfn=`echo "$fn"|iconv -f utf-8 -t ascii//translit`
  newfn=${newfn// /_}
  newfn=${newfn//\'/_}
  newfn=${newfn//\`/_}
  newfn=${newfn//(/_}
  newfn=${newfn//)/_}
  newfn=${newfn//[/_}
  newfn=${newfn//]/_}
  newfn=${newfn//!/_}
  newfn=${newfn//&/_}
  newfn=${newfn//+/_}
  newfn=${newfn//:/_}
  newfn=${newfn//;/_}
  newfn=${newfn//\"/_}
  newfn=${newfn//,/_}
  newfn=${newfn//\?/_}
  newfn=${newfn//=/_}
  newfn=${newfn//%/_}
  newfn=${newfn//#/_}
#   newfn=${newfn//\á/a}
#   newfn=${newfn//\à/a}
#   newfn=${newfn//\é/e}
#   newfn=${newfn//\è/e}
#   newfn=${newfn//\í/i}
#   newfn=${newfn//\ó/o}
#   newfn=${newfn//\ö/o}
#   newfn=${newfn//\ő/o}
#   newfn=${newfn//\ú/u}
#   newfn=${newfn//\ü/u}
#   newfn=${newfn//\ű/u}
#   newfn=${newfn//\Á/A}
#   newfn=${newfn//\É/E}
#   newfn=${newfn//\È/E}
#   newfn=${newfn//\Í/I}
#   newfn=${newfn//\Ó/O}
#   newfn=${newfn//\Ö/O}
#   newfn=${newfn//\Ő/O}
#   newfn=${newfn//\Ú/U}
#   newfn=${newfn//\Ü/U}
#   newfn=${newfn//\Ű/U}
  
  newi="$pathname/$newfn"
  if [ "$i" != "$newi" ]
  then
   if [ -f "$newi" ]
   then
    echo "$newi exists, skipping $i"
   else
    echo "$i --> $newi"
    mv "$i" "$newi"
   fi
  fi
 fi
done
