#!/bin/bash
# 2016-12-23

# Cleans up all filenames in the directory.

for i in *
do
 if [ -f "$i" ]
 then
   newfn=`echo "$i"|iconv -f utf-8 -t ascii//translit`
   newfn=${newfn// /_}
   newfn=${newfn//\'/_}
   newfn=${newfn//\`/_}
   newfn=${newfn//(/_}
   newfn=${newfn//)/_}
   newfn=${newfn//[/_}
   newfn=${newfn//]/_}
   newfn=${newfn//!/_}
   newfn=${newfn//&/_}
   newfn=${newfn//+/_}
   newfn=${newfn//:/_}
   newfn=${newfn//;/_}
   newfn=${newfn//\"/_}
   newfn=${newfn//,/_}
   newfn=${newfn//\?/_}
   newfn=${newfn//=/_}
   newfn=${newfn//%/_}
   newfn=${newfn//#/_}
#   newfn=${newfn//\á/a}
#   newfn=${newfn//\à/a}
#   newfn=${newfn//\é/e}
#   newfn=${newfn//\è/e}
#   newfn=${newfn//\í/i}
#   newfn=${newfn//\ó/o}
#   newfn=${newfn//\ö/o}
#   newfn=${newfn//\ő/o}
#   newfn=${newfn//\ú/u}
#   newfn=${newfn//\ü/u}
#   newfn=${newfn//\ű/u}
#   newfn=${newfn//\Á/A}
#   newfn=${newfn//\É/E}
#   newfn=${newfn//\È/E}
#   newfn=${newfn//\Í/I}
#   newfn=${newfn//\Ó/O}
#   newfn=${newfn//\Ö/O}
#   newfn=${newfn//\Ő/O}
#   newfn=${newfn//\Ú/U}
#   newfn=${newfn//\Ü/U}
#   newfn=${newfn//\Ű/U}
  
  if [ "$i" != "$newfn" ]
  then
   if [ -f "$newfn" ]
   then
    echo "$newfn exists, skipping $i"
   else
    echo "$i --> $newfn"
    mv "./$i" "./$newfn"
   fi
  fi
 fi
done
