#!/bin/bash
mkdir kul
for i in *; do
 #echo "i: $i"
 if [[ -f "$i" && -f "$1/$i" ]]
  then
  cmp -s "$i" "$1/$i"
  if [ "$?" -ne "0" ]
    then
    echo "$i"
    cp "$i" kul/
   vimdiff "kul/$i" "$1/$i" -c "wincmd l" -c "se ro" -c "se nomodifiable"
  fi
 fi
done
